services:
  - type: web
    name: portfolio-site
    env: node
    repo: https://github.com/Subbu-Laxmi/Portfolio
    branch: master          # or main
    buildCommand: npm install
    startCommand: npm start
    pullRequestPreviewsEnabled: true
    plan: free
